Feature/jc19 427 authorization  [Angular]
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #10
Opened 2022-08-04 08:38 UTC by andrey-gazzaev

#19-427

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/auth.component.css
> +app-auth .auth-form {
Do you really need to write `app-auth` in every selector? If so, explain why with comment in the code.

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/header/header.component.html
> +          type="button"
Here you have a link, that only look like button. So you should omit `type="button"`

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.html
> +    >
I see that you repeating this code in registration. I suggest extracting it into a component like `input-password` or something.

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +      }) : throwError(() => new AppError(UNAUTHORIZED_ERROR))),
```suggestion
      switchMap(tokens => tokens !== null ?
        this.http.post<TokenDto>(this.refreshUrl.toString(), {
          refresh: tokens.refresh,
        }) :
        throwError(() => new AppError(UNAUTHORIZED_ERROR))
      ),
```

2022-08-05 04:28 UTC, artem-sotnichenko-saritasa commented on libs/core/utils/guards/general.guard.ts
> +    }
```suggestion
    if (Object.prototype.hasOwnProperty.call(fields, key) && !isDefined(fields[key])) {
      return false;
    }
```

2022-08-05 04:38 UTC, timofei-maximov-saritasa approved these changes

2022-08-05 09:34 UTC, chernodub requested changes
Thanks for a good job 👍

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +      formControlName="password"
To enhance UX of your app, prefer specifying an [`autocomplete`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) attrubute

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +  </p>
For me, it seems that putting a button inside a `p` is a questionable solution, because `p` has a semantical meaning. _Paragraphs are usually represented in visual media as blocks of text separated from adjacent blocks by blank lines and/or first-line indentation, but HTML paragraphs can be any structural grouping of related **content**, such as images or form fields._

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +      <a class="link" mat-button title="Password recovery" href="#"
I believe that for links containing representative text, there is no point specifying a title :)

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.ts
> +          }
This is a perfect example of "leaked abstraction". Your [repository](https://wiki.saritasa.rocks/frontend/frameworks/architecture/#repository)-related entity is used on [view layer](https://wiki.saritasa.rocks/frontend/frameworks/architecture/#view). Please remember, your components must never know anything about HTTP, DTO, data-mapping, etc. By following this segregation of layers, you're going to make your code waaay more maintainable. Actually, you are very close with your implementation of `HttpError`. From my perspective, the only issue you have here is the name of the error, that exposes its relation to repository layer

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +  public isHiddenPasswordConfirm = true;
Whenever you see such repetition of view/state, please always consider moving this into a component

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +    }
Angular provides great [validators API](https://angular.io/guide/form-validation). So, for this password validation, you could create a custom validator.

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/core/services/token.service.ts
> +    );
Very smart 👍👍👍

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/core/services/user.service.ts
> +  public login(loginData: LoginData): Observable<void | RegistrationErrors> {
1. Probably you meant `LoginErrors`
2. Observable errors are never specified in the type declaration of this observable, this just is how rxjs works (like in JS, you never specify type of errors a function could throw).

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/core/services/user.service.ts
> +      catchError(() => of(null)),
Usually, silencing errors is a bad practice that may cost you hours of debugging. So, in such cases, I recommend at least having a warning and specify why you ignore the error

2022-08-05 09:34 UTC, chernodub commented on apps/angular/src/core/utils/show-errors.ts
> +export function showSnackBarError(message: string | undefined, snackBar: MatSnackBar): void {
You could create a service for this. So as not to pass snackbar every time :)

2022-08-05 09:34 UTC, chernodub commented on libs/core/mappers/registration-data.mapper.ts
> +    const avatar =
Probably, this placeholder logic should be handled by UI layer, rather than repository. What if, at some point, team decides to use some CSS-made graphics in case of non-existent avatar ? :)

2022-08-08 17:05 UTC, kristinaSvobodinaSaritasa approved these changes

2022-08-08 17:05 UTC, kristinaSvobodinaSaritasa commented on apps/angular/src/core/services/user.service.ts
> +   * Log шn.
Typo

2022-08-09 04:04 UTC, dbitkovski commented on apps/angular/src/core/services/auth.service.ts
> +const UNAUTHORIZED_ERROR = 'User unauthorized';
```suggestion
const UNAUTHORIZED_ERROR_MESSAGE = 'User unauthorized';
```
It's just a string, not an `Error` object :)

2022-08-09 06:13 UTC, viktor-sakhno-saritasa approved these changes

2022-08-09 06:13 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/auth/registration/registration.component.ts
> +      email: ['test@test.com', [Validators.required, Validators.email]],
Yes, adding a placeholder for this input is enough.

2022-08-10 02:44 UTC, pavel-romanov8 requested changes

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/login/login.component.html
> +  (submit)="handleFormSubmit()"
Prefer using `ngSubmit` instead. That way, we are relying on the API that `formGroup` directive provides instead of native `form` API

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/password-input/password-input.component.ts
> +  styleUrls: ['../auth.component.css'],
The same about change detection strategy

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/password-input/password-input.component.ts
> +  public isHiddenPassword = true;
```suggestion
  public isPasswordHidden = true;
```

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/app/features/auth/registration/registration.component.html
> +  (submit)="onFormSubmit()"
```suggestion
  (ngSubmit)="onFormSubmit()"
```

2022-08-10 02:44 UTC, pavel-romanov8 commented on libs/core/utils/guards/general.guard.ts
> +export function isFieldsDefined<T>(fields: T): fields is NonNullableFields<T> {
Are you using it anywhere?

2022-08-10 02:44 UTC, pavel-romanov8 commented on libs/core/models/token.ts
> +export class Token extends Immerable {
Please, update documentation for the class as well

2022-08-10 02:44 UTC, pavel-romanov8 commented on libs/core/models/registration.ts
> +
Redundant empty line

2022-08-10 02:44 UTC, pavel-romanov8 commented on libs/core/mappers/registration-data.mapper.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
Not sure why do we need to disable linter here. Please, leave some comments on why are doing so

2022-08-10 02:44 UTC, pavel-romanov8 commented on libs/core/mappers/login-data.mapper.ts
> +    return model;
Even if your model and DTO has the same interface, we should just return the model. The reasoning is simple, we are always see relations with model-DTO fields and in case some of them changes we are able to detect which field is changed instantly

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +      map(() => false),
As I see you are not relying on the function output in any way, so there is no need to return boolean, it can be just `Observable<void>`

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +  public fetchUser(): Observable<User | null> {
Please, check the [architecture section](https://wiki.saritasa.rocks/frontend/frameworks/architecture/) in our wiki. We shouldn't expose that the service is working with any request, because it is a leak of abstraction. If you have any questions, feel free to ask me

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +  public register(registrationData: Registration): Observable<boolean> {
The same thing about function output here and in `login` method

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +  public fetchUser(): Observable<User | null> {
Also, i see that you are not using the method outside the service, so it can be `private`

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +export interface RegistrationErrors {
Not sure what is the point of having those interfaces here, when you are using them only on UI layer

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/user.service.ts
> +export interface RegistrationErrors {
Also, i see that the keys are basically duplicate keys from domain models. Let's create a util type that will transform the domain model to such form

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/auth.service.ts
> +      'user_avatars%2Ff33c09a7-a15e-4b7c-b47f-650bfe19faff%2Fprofile.jpg';
Why is it hardcoded?

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/auth.service.ts
> +      'https://s3.us-west-2.amazonaws.com/camp-js-backend-files-dev/' +
Please, move S3 URL to variables

2022-08-10 02:44 UTC, pavel-romanov8 commented on apps/angular/src/core/services/auth.service.ts
> +            switchMapTo(this.urlService.navigateToLogin()),
Please, avoid using `switchMapTo` and all `To` operators since they will be deprecated. Instead, we can write it like so:
```ts
switchMap(() => this.urlService.navigateToLogin()),
```

2022-08-10 12:13 UTC, chernodub approved these changes
Pls resolve the rest of the suggestions by the guys

2022-08-10 12:13 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +  <header class="form-header">
Seems weird that you use element in a foreign block, as far as I remember it is prohibited to mix such stuff, otherwise it's going to be a pain in the ass extracting these components. Consider making `form-header` an element of `auth-form` block

2022-08-10 12:13 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +    </mat-error>
How about handling `required`? I'd recommend coming up with some generic solution for displaying errors. Consider checking out [this library](https://github.com/ngneat/error-tailor)

2022-08-10 12:13 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +  </mat-list>
According to docs:
_If the list is used to present a list of **non-interactive content items**, then the list element should be given role="list" and each list item should be given role="listitem"._

In your case, the elements are interactive and probably you should omit `role`

2022-08-12 05:06 UTC, andrey-gazzaev commented on libs/core/utils/guards/general.guard.ts
> +export function isFieldsDefined<T>(fields: T): fields is NonNullableFields<T> {
I used it in a previous implementation, but it is not used now. I think it's not a bad util that can be used in other implementations. It can be useful when I don't use the form builder.

2022-08-12 05:13 UTC, andrey-gazzaev commented on libs/core/mappers/registration-data.mapper.ts
> +/* eslint-disable @typescript-eslint/naming-convention */
It is necessary to use snake case for mapping in DTO. I will add a comment.

2022-08-12 05:39 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +      'user_avatars%2Ff33c09a7-a15e-4b7c-b47f-650bfe19faff%2Fprofile.jpg';
An avatar is required to register. This picture is already uploaded to s3.

2022-08-12 07:29 UTC, andrey-gazzaev commented on apps/angular/src/core/services/auth.service.ts
> +            switchMapTo(this.urlService.navigateToLogin()),
Discussed

2022-08-16 05:52 UTC, merged