Feature/jc19 455 initialize anime app and authorization feature [React]
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #14
Opened 2022-08-19 03:14 UTC by andrey-gazzaev

#JC19-455

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/App.tsx
>          <Suspense fallback={<div>Brrr... here should be your loader component</div>}>
Let's replace it :)

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/api/interceptors.ts
> + * @param config - Request config.
```suggestion
 * @param config Request config.
```

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/api/services/userService.ts
> +    const userDto = (await http.get<UserDto>(userUrl.toString())).data;
```suggestion
    const { data } = await http.get<UserDto>(userUrl.toString());
```

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/components/Header/Header.tsx
> +const HeaderComponent = () => {
Don't forget to add type for component.

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +  });
Please, provide types for `useState`. Also, remove duration from here, since you don't change it.

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +  };
Wrap it with `useCallback`

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +  const isSubmitForm = useAppSelector(selectAreAuthSubmit);
Let's improve naming here. `isFormSubmitted` sounds better.

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/RegistrationForm/RegistrationForm.tsx
> +            />
There are a lot of duplicated code. You can use https://github.com/stackworx/formik-mui or make wrapper for working with formik by yourself

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/RegistrationForm/RegistrationForm.tsx
> +  };
Don't forget to add docs for your functions

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/routes/guards/noneAuthGuard.tsx
> +import { memo } from 'react';
File name should be in `PascalCase`

2022-08-19 03:43 UTC, timofei-maximov-saritasa commented on apps/react/src/store/auth/state.ts
> +  readonly isSubmit: boolean;
`isSubmitted`

2022-08-19 03:52 UTC, panov-aleksey-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +  };
@timofei-maximov-saritasa please, provide an examplanation why it should be added. If I am not mistaken, we haven't covered usage of  `useCallback` yet

2022-08-19 04:11 UTC, golovachev-yaroslav requested changes

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/components/Header/Header.tsx
> +            <Button type='button' color="inherit" onClick={handleUserLogout}>Log Out</Button>
`type='button'`, please use double quote for static props.

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +      <HeaderForm label='Sign In' />
double quotes, please.

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +      <Box component="form" noValidate onSubmit={formik.handleSubmit} >
Unnecessary empty space before `>`

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/RegistrationForm/RegistrationForm.tsx
> +export const RegistrationFormComponent = () => {
Missed type.

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/routes/guards/noneAuthGuard.tsx
> +    return < Navigate to={redirect} replace />;
Empty space between `<` and `Navigate`.

2022-08-19 04:11 UTC, golovachev-yaroslav commented on apps/react/src/routes/guards/restoreGuard.tsx
> +
PLease remove empty line.

2022-08-19 04:36 UTC, panov-aleksey-saritasa commented on apps/react/src/components/Header/Header.tsx
> +            <Button type='button' color="inherit" onClick={handleUserLogout}>Log Out</Button>
@golovachev-yaroslav  I think it's a thankless job to manage such things manually. Is there a way to automatize it? Maybe do you know some eslint rule for this? We could add it to boilerplate 🙂

2022-08-19 05:15 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +  };
@panov-aleksey-saritasa I mentioned `useCallback` because I saw usage of it in code. I assume, that @andrey-gazzaev used it intentionally.

2022-08-20 09:23 UTC, andrey-gazzaev commented on apps/react/src/routes/guards/restoreGuard.tsx
> +
If I understood everything correctly, I need to remove empty lines after
``` interface Props { ```
But we have a ESLint rule: Expected line before comment.eslint[lines-around-comment]
(https://eslint.org/docs/rules/lines-around-comment)

2022-08-22 06:31 UTC, viktor-sakhno-saritasa approved these changes

2022-08-22 06:31 UTC, viktor-sakhno-saritasa commented on apps/react/src/features/auth/components/HeaderForm/HeaderForm.module.css
> +.header__text {
I consider renaming to `.header__label` because in the component you use header label prop. I think, it is more clear, when your CSS class reflects content inside elements.

2022-08-22 06:31 UTC, viktor-sakhno-saritasa commented on apps/react/src/routes/guards/NoneAuthGuard.tsx
> +};
Please, be consistent. In `AuthGuard` you use ternary operator instead of a condition. I suggest choosing one approach and sticking with it.

2022-08-23 05:12 UTC, pavelzadorin-saritasa requested changes

2022-08-23 07:50 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-08-23 07:50 UTC, gevorg-gevorgyan-saritasa commented on apps/react/src/store/auth/state.ts
> +  /** Whether or not it has been submit. */
```suggestion
  /** Whether it has been submitted or not. */
```

2022-08-25 08:03 UTC, chernodub requested changes

2022-08-25 08:03 UTC, chernodub commented on apps/react/src/components/Header/Dashboard/Dashboard.tsx
> +        id="basic-button"
Since it's a component-based SPA, we can not guarantee this component is not used twice. And id must be unique on a page. Please prefer [`useId`](https://reactjs.org/docs/hooks-reference.html#useid) for generating unique ids

2022-08-25 08:03 UTC, chernodub commented on apps/react/src/components/Header/Dashboard/Dashboard.tsx
> +  const open = Boolean(anchorEl);
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#is

2022-08-25 08:03 UTC, chernodub commented on apps/react/src/components/Header/Header.tsx
> +            Anime Catalog
Please prefer consistent indends, I'd appreciate if you could set up your eslint for watching this

2022-08-25 08:03 UTC, chernodub commented on apps/react/src/components/Header/Header.tsx
> +            Anime Catalog
BTW, seems weird that your generic Header component knows the specific name of the page. Consider passign this as a prop

2022-08-26 10:14 UTC, closed without merging