Feature/jc19 477 anime list management
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #16
Opened 2022-08-22 05:48 UTC by andrey-gazzaev

#JC19-477

2022-08-22 11:55 UTC, golovachev-yaroslav approved these changes

2022-08-22 11:55 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeList/AnimeList.tsx
> +    <Paper className={styles['animeCatalog']}>
I think you can do it more simple `styles.animeCatalog`

2022-08-23 13:15 UTC, artem-sotnichenko-saritasa approved these changes
I think you have problems with UX. The inputs are small, and look too packed. "Search" and "type" buttons are unnecessary tall, because "sort" is tall. To fix it, you could place them on new lines, use tabs, or use popup.
Also, if select only type and sort, block is overflowing.

2022-08-23 13:15 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/ToggleInput/ToggleInput.module.css
> +  background: #f5f5f5;
Please move color values into variables.

2022-08-24 06:50 UTC, timofei-maximov-saritasa requested changes

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/api/services/animeService.ts
> +  export async function fetchAnimeList(animeListQueryParams: AnimeListQueryParams): Promise<readonly AnimeBase[]> {
Do not force to users to work with `readonly` against their will.

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/AnimeList/AnimeList.tsx
> +                <React.Fragment key={anime.id} >
No need to import `React` you can import `Fragment` from `react`

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/QueryBar/QueryBar.tsx
> +
Extra empy line

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/QueryBar/QueryBar.tsx
> +  const handleTabChange = useCallback((event: React.SyntheticEvent, newTabNumber: number) => {
```suggestion
  const handleTabChange = useCallback((event: SyntheticEvent, newTabNumber: number) => {
```

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/QueryBar/QueryBar.tsx
> +  const handleSearchChange = useCallback((event: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
```suggestion
  const handleSearchChange = useCallback((event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
```

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/features/anime/components/QueryBar/QueryBar.tsx
> +          <Button onClick={handleDirectionToggle}>
Missing `type` attribute

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/store/anime/dispatchers.ts
> +);
There is no need to use thunk for this action, there is no point in such action. You can use `reducer` for this purpose.

2022-08-24 06:50 UTC, timofei-maximov-saritasa commented on apps/react/src/store/anime/slice.ts
> +      entityAdapter.removeAll(state as State);
Let's use reducers over extraReducers here

2022-08-26 10:14 UTC, closed without merging