Feature/jc19 487 displaying details for a selected anime [React]
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #17
Opened 2022-08-24 04:40 UTC by andrey-gazzaev

#JC19-487

2022-08-24 16:46 UTC, artem-sotnichenko-saritasa approved these changes
https://saritasa-nest.github.io/camp-js-2022-andrey-gazzaev/pr-preview/pr-17/#/anime?search=&types=TV&field=english&direction=des&id=10929
On my screen, youtube player is cropped and I can't scroll.

2022-08-24 16:46 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/Details/Details.module.css
> +.details .placeholderTest {
I think you made a typo.

2022-08-24 16:46 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime/components/ImagePopup/ImagePopup.tsx
> +      <img src={imageSrc} alt="" />
I think you should provide `alt` with a prop

2022-08-25 13:20 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/Details/Details.tsx
> +    'no date' :
no date repeats many times, let's move it con const.

2022-08-26 02:44 UTC, AndreySkripachev commented on apps/react/src/api/services/animeService.ts
> +      const url = `${animeUrl.toString()}${id}/`;
```
new URL(id, animeUrl.toString())
```

2022-08-26 02:53 UTC, AndreySkripachev commented on apps/react/src/features/anime/components/AnimeList/AnimeList.tsx
> +  const [currentAnimeId, setCurrentAnimeId] = useState(query.id);
Is it really necessary?

2022-08-26 07:13 UTC, chernodub requested changes

2022-08-26 07:13 UTC, chernodub commented on package.json
> +    "moment": "^2.29.4",
Moment is considered to be deprecated, please prefer some more modern solutions
https://momentjs.com/docs/#/-project-status/

2022-08-26 10:14 UTC, closed without merging