Feature/jc19 326 init app table view
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #3
Opened 2022-07-01 09:37 UTC by andrey-gazzaev

Made an anime table, pagination and sorting.

2022-07-01 10:36 UTC, elena-dragunova requested changes

2022-07-01 10:48 UTC, golovachev-yaroslav requested changes

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/fetches/anime.ts
> +import axios from 'axios';
Usually import external libs and then developer's.

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +@import url("../global/variables.css");
`<link>` is preferred in all cases over @import, because the latter blocks parallel downloads, meaning that the browser will wait for the imported file to finish downloading before it starts downloading the rest of the content.

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +.catalog__table .catalog__table-row > .catalog__table-body,
Too many nesting, why not `.catalog__table-body` ?

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +  span.classList.add(...classes.map(c => c.replace('.', '')));
You can use React approach - class = className.

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/public.ts
> +  document.documentElement.scrollTop = 0;
FYI: we don't support Opera and IE.

2022-07-01 10:48 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/table.ts
> +      const aired = anime[TableColumns.Aired].start !== null ?
`anime[TableColumns.Aired].start` repeats many times, what about to move in into const?

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/pagination.ts
> + * @returns An array of borders where the first element is the left border and the second element is the right border.
You return 3 elements, but describe only 2

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/constants/attribute.ts
> +export namespace AttributeName {
Add docs, please.

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/constants/public.ts
> +export const FIRST_PAGE = 1;
Add docs, please. You have two constants PAGE_OFFSET and DEFAULT_OFFSET and I can't understand, what they contain.

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const lastPage = Math.floor(allAnimeCount / DEFAULT_OFFSET);
Are you sure that it is correct? For example, Math.floor(100/30) return 3, but the last page should be 4 in this case?

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  if (currentPageNumber <= allAnimeCount) {
I can't understand why you need to compare `currentPageNumber` and `allAnimeCount`, is there the case when `currentPageNumber` will be bigger than `allAnimeCount`?

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/pagination.ts
> +function createButton(pageNumber: number, classes: readonly string[]): HTMLButtonElement {
As I can see from your code, you call this function all times with [Catalog.BUTTON_PAGINATION], and in only one case you add also Catalog.PAGINATION_BUTTON_CURRENT, I think it will be better implement classes in this function, no need to complicate the logic by adding the array of class, add some flag isCurrentPage:boolean.

2022-07-01 10:50 UTC, kristinaSvobodinaSaritasa commented on apps/vanilla/src/scripts/table.ts
> +    row.classList.add(Catalog.TABLE_ROW.replace('.', ''));
There are a lot of copy past code `class.replace('.',''`), if you are really need this logic, maybe it will be better use some custom function getClassName?

2022-07-01 10:55 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.css
> +@import url("../global/variables.css");
The Vite project builder builds them all @Import one css file.

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa requested changes

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
>    --heading-color-3: powderblue;
It was for presentation purpose in boilerplate. Now if you using hex, either remove heading colors vars or convert them into hex.

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.css
> +@import url("../global/variables.css");
@golovachev-yaroslav We discussed with team and decided to use `@import` for these reasons:
- Vite bundles `@import`s and `<link>`s into single file 🤯.
- Vite with multi route approach is not working with `<link>`s that leads into other dirs, for some reason.
If you want more in-depth explanation, message me in slack.

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  button.addEventListener(Event.CLICK, changeAnimeData.bind(null, pageNumber));
Why are you using bind here?

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +function definingPaginationBoundaries(
[Please use verb when naming function ](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions)

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/public.ts
> +    'limit=25&',
I seen you have a constant with a value 25, perhaps it belongs here?

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/sort.ts
> +        handleChangeSortSettings.bind(null, selectElement, select.sortName),
I think you forget to remove `.bind` after refactoring

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/table.ts
> +    row.classList.add(Catalog.TABLE_ROW.replace('.', ''));
I think it would be better to remove dot in you constants. Instead of removing dot, add it when needed, like so:
```js
document.querySelector(`.${Catalog.TABLE}`);
```

2022-07-03 06:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/table.ts
> +          break;
I think it is advanced topic, and you don't need to implement it.
But you may read about "Exhaustive type checking" in your **free time**, this is [a great article](https://dev.to/babak/exhaustive-type-checking-with-typescript-4l3f).

2022-07-04 04:20 UTC, andrey-gazzaev commented on apps/vanilla/src/scripts/public.ts
> +  document.documentElement.scrollTop = 0;
Should I remove this code?

2022-07-04 04:23 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/public.ts
> +  document.documentElement.scrollTop = 0;
I think you can implement scroll using https://developer.mozilla.org/ru/docs/Web/API/Window/scrollTo
```
window.scrollTo({
    top: 0,
    behavior: "smooth"
});
```

2022-07-04 05:24 UTC, maxineo commented on apps/vanilla/src/scripts/public.ts
> +  return urlParts.join('');
Could you just return template string?

2022-07-04 05:24 UTC, maxineo commented on apps/vanilla/src/scripts/table.ts
> +  return updateTableAnime(tableRows);
The same with `return`.

2022-07-04 05:31 UTC, andrey-gazzaev commented on apps/vanilla/src/scripts/public.ts
> +  return urlParts.join('');
@maxineo If I write everything in one line, then it will be very long. I wanted to avoid this and made an array consisting of endpoint and queries.

2022-07-04 08:31 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-04 08:32 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-04 09:33 UTC, timofei-maximov-saritasa requested changes

2022-07-04 09:33 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly end: Date;
I guess you receive date sting from server. But here in dto you have `Date` type

2022-07-04 11:37 UTC, golovachev-yaroslav approved these changes

2022-07-04 11:37 UTC, golovachev-yaroslav commented on apps/vanilla/src/fetches/anime.ts
> +      console.warn(detail);
Does it really need?

2022-07-04 11:37 UTC, golovachev-yaroslav commented on apps/vanilla/src/fetches/instance.ts
> +    baseURL: import.meta.env.VITE_BASE_URL,
I think it should me a imported const, not directly vite calling.

2022-07-05 05:07 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-05 05:37 UTC, panov-aleksey-saritasa requested changes

2022-07-05 05:37 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/public.ts
> + */
Prefer [inline docs](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#docstring-or-inline) whenever it's possible

2022-07-05 05:37 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  return [prevPage, nextPage, lastPage];
You are the first one who implement this stuff without `let`, good job 👍

2022-07-05 05:37 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +}
Rather than hardcode `width`/`height`, consider using more flexible and robust approach with `min-height(width)`/`max-height(width)`.
We have the section about it in [wiki](https://wiki.saritasa.rocks/frontend/languages/css#dont-set-hardcoded-size)
Also you could check this article https://ishadeed.com/article/defensive-css/, it contains section about hardcoded sizes, but also has some useful advices about css styling overall

2022-07-05 05:37 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/constants/animeTable.ts
> +/** Anime Table Columns. */
You can leave as it is, but actually I don't like approach with placing such stuff into global `constants` folder.  In my opinion, you should place things in scope where they are the most relevant. For example, if you have some general purpose function for, let's say, formatting dates, you could place it somewhere at the global level since it could be used anywhere across the app, but if you have some narrow-specific thing that is probably going to be used only once and only in specific place, better keep it somewhere near this specifc place.

2022-07-05 06:07 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/index.html
> +            <select name="direction" class="form__select catalog__sort-direction"></select>
https://ru.bem.info/methodology/quick-start/#%D0%BF%D1%80%D0%B8%D0%BD%D1%86%D0%B8%D0%BF-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0%D0%BC%D0%B8

@panov-aleksey-saritasa As far as I understand, blocks can be nested in each other.

"
Вложенность
Блоки можно вкладывать друг в друга.

Допустима любая вложенность блоков.
"

2022-07-05 06:33 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.html
> +            <select name="direction" class="form__select catalog__sort-direction"></select>
Yes, like in the component-based approach one block could consist of any other blocks, but what I meant here is that your `catalog` block is leaking inside the  `form` block (the `class="form__select catalog__sort-direction"` part ) and therefore interferes with the `form` inner organization.

2022-07-05 19:23 UTC, chernodub requested changes

2022-07-05 19:23 UTC, chernodub commented on apps/vanilla/src/pages/index.css
> +.catalog {
Consider revising your BEM structure on this page. You only have a single `catalog` block, probably you can destructure this a bit for better reusability and maintainability

2022-07-05 19:23 UTC, chernodub commented on apps/vanilla/src/pages/index.css
> +.catalog__pagination-btn {
Although `btn` is already a well-established abbreviation for a button. As a rule of thumb, we prefer not to use contractions at all https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-05 19:23 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +<body class="page__body">
BEM elements can not be present without a parent block. Probably this should just be a `page`

2022-07-07 11:21 UTC, panov-aleksey-saritasa commented on libs/core/models/anime.ts
> +}
Please, remove `Anime` from property docs and move out this class into separate file. The whole meaning behind renaming `Aired` to `DateRange` was about to uncouple it from `Anime` and to make it independent and reusable entity, right?

2022-07-07 11:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/fetches/anime.ts
> +  }
Actually, you could right your own `get` implementation based on `axios.get` and add there this stuff with throwing `HttpError`. Otherwise you would have to right this `try/catch` piece of code for every such function

2022-07-07 11:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/public.ts
> +
Your UI layer shouldn't know anything about how to create URLs for fetch queries, instead it should only gather user inputs and then pass them to the functions or services that are responsible for making valid requests out of received data

2022-07-07 11:21 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/public.ts
> +
It's well described [here](https://wiki.saritasa.rocks/frontend/frameworks/angular/architecture#view)

2022-07-07 13:06 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/types/sortSettings.ts
> +  [index: string]: string;
Missing `readonly`

2022-07-07 13:06 UTC, timofei-maximov-saritasa commented on libs/core/models/anime.ts
> +  /** Release and end dates. */
```suggestion
  /** Release start and end dates. */
```

2022-07-07 14:11 UTC, chernodub requested changes

2022-07-07 14:11 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  return [prevPage, nextPage, lastPage];
Following this logic, where's the first page then? :) Try to be more consistent in such things

2022-07-07 14:11 UTC, chernodub commented on apps/vanilla/src/scripts/public.ts
> +    `offset=${offset}&`,
Consider using `URLSearchParams` for handling query params, please

2022-07-07 14:11 UTC, chernodub commented on libs/core/dtos/anime.dto.ts
> +  readonly type: string;
For the properties that have a pool of available options, please prefer one of the following:
* enum
* inline string union (`'TV' | 'OVA' ...`)
* aliased string union (`type AnimeType = 'TV' | 'OVA' ...`)

This will increase the readability/maintainability of your code. Also, you won't need to specify this stuff in the docs

2022-07-07 14:11 UTC, chernodub commented on libs/core/dtos/anime.dto.ts
> +  readonly status: string;
Same recommendation as above

2022-07-08 06:37 UTC, golovachev-yaroslav approved these changes

2022-07-09 10:30 UTC, golovachev-yaroslav approved these changes

2022-07-11 05:18 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/types/paginationSettings.ts
> +}
I think you could move out this interface to the `core` models, also make it more flexible via replacing `field` property with generic

2022-07-11 05:18 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/types/anime.ts
> +  readonly totalAnimeCount: number;
Consider not duplicating context ([wiki](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-context-duplication)), it's already clear that you are working with `Anime` entites 🙃

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/UI/tableView/pagination.ts
> +  lastPage: number,
I think it should be object with `PaginationBorders` type

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/UI/tableView/sort.ts
> +      return selectElement.addEventListener(
Why do you have `return` in `forEach`?

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/helpers/guards.ts
> +}
Please, be consistent with your docs. Check it everywhere.
```suggestion
/**
 * Checks if the error is of type HttpErrorDto.
 * @param error Some error.
 */
export function isHttpErrorDto(error: unknown): error is HttpErrorDto {
  return (error as HttpErrorDto).detail !== undefined;
}

/**
 * Checks if a value is of a enum Status.
 * @param value Some string.
 */
export function isStatus(value: string): value is Status {
  return Object.values(Status).includes(value as Status);
}
```

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on libs/core/dtos/anime.dto.ts
> +}
Why do you need generic here?

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper.ts
> +      aired: mapperFromDto(dto.aired),
There is no need to pass mapper here. Just use it directly
```suggestion
      aired: DateRangeMapper.fromDto(dto.aired),
```

2022-07-11 05:39 UTC, timofei-maximov-saritasa commented on libs/core/dtos/dateRange.dto.ts
> +  readonly start: string;
According to api docs these fields are `nullable`

2022-07-11 06:45 UTC, golovachev-yaroslav approved these changes

2022-07-12 13:28 UTC, panov-aleksey-saritasa approved these changes

2022-07-13 19:42 UTC, chernodub requested changes

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/constants/classes.ts
> +export namespace TableBlock {
Seems like this was not resolved https://github.com/saritasa-nest/camp-js-2022-andrey-gazzaev/pull/3#discussion_r915851170 :(

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> + * @param allAnimeCount All records that the server can provide.
Your UI layer should not know anything about "server". What if you decide to make your application serverless? It's not going to be smooth if you don't keep your abstraction layers, right?

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> + * @param allAnimeCount All records that the server can provide.
Consider revising this https://wiki.saritasa.rocks/frontend/frameworks/angular/architecture

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> + * @param pageNumber The page number the button contains.
Pls fix grammar in this sentence

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> + * @returns Span element.
Consider omitting comments that are already obvious from the type signature and are not required by linter

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> +
The comment above is not answered/resolved, but only marked as "resolved". Please either answer a comment or resolve it in your code @andrey-gazzaev

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> +
If you received a comment with which you do not agree, you must not _resolve_ it silently. Answer it, and make sure the person who left the comment agreed with you (or the opposite). Only then a comment may be considered as _resolved_

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> +    buttonsPagination.push(createSpan(ELLIPSIS, []));
Probably you could use a default `[]` for second parameter

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> +function createButton(pageNumber: number, isCurrentPage: boolean): HTMLButtonElement {
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#how-to-pass-arguments-to-functionsmethods

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/pagination.ts
> +function updatePaginationElement(buttons: readonly (HTMLButtonElement | HTMLSpanElement)[]): void {
Seems like it's not only buttons, but also spans? Make sure your type declaration is consistent with your names at all times :)

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/sort.ts
> +  const paginationOptions = LocalStorageService.getValue<PaginationOptions>(LocalStorageKey.PAGINATION_SETTINGS);
Usually, it's a better practice to store the pagination/sort/filter information in the query parameters of the application. This way we can preserve/share the state of filter/sort/pagination. You can omit this change for now, but please stick to this recommendation in your next 2 projects 👍

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/sort.ts
> +    } else if (isSortOrdering(selectValue)) {
As far as I understood, I am unable to apply both the ordering and field options? Why so, what if I decide to sort by ascending/descending value of `Aired` field?

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/table.ts
> +    Object.values(TableColumn).forEach(column => {
This logic is going to be broken if you ever decide to make your enum heterogeneous, try adding a numeric value into your enum and see what happens :)

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/table.ts
> +      thElement.classList.add(Table.BODY);
Is this a mistake? From the perspective of a code reader, this looks weird, why would you add a table body class to `td`? Basically, it's something like `td = tbody`

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/table.ts
> +          imageElement.alt = `Image of anime ${anime.titleEnglish}`;
For screen readers, it is already obvious that this is an image. Consider putting only semantically valuable text in `alt` attribute

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/UI/tableView/table.ts
> +      const thElement = document.createElement('td');
Is it `th` or `td` after all?

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/constants/animeTable.ts
> +export const NO_DATA = '-';
This is a UI-specific information, consider moving it out of your domain-related modules

2022-07-13 19:42 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +            <label class="form__label" for="sort-field">
To avoid the need of `.field` container and `id`/`for` attributes, you can nest your controls into labels the following way (it is identical, but easier to read/maintain):
```html
            <label class="form__label">
              <span class="form__label-text">Sort by:</span>
              <select name="fields" class="form__select sort-field"></select>
            </label>
            
```

2022-07-14 02:12 UTC, andrey-gazzaev commented on apps/vanilla/src/UI/tableView/sort.ts
> +    } else if (isSortOrdering(selectValue)) {
Sorting, filtering and ordering is divided into selectors. Thus, you can select several options at once. This implementation assumes that the local storage will be written to every time the fields are changed.

```
      filter = { ...paginationOptions.filter, byStatusField: selectValue };
    } else if (isSortField(selectValue)) {
      sort = { ...paginationOptions.sort, field: selectValue };
    } else if (isSortOrdering(selectValue)) {
```
This condition simply checks which field to write to.

2022-07-14 08:39 UTC, andrey-gazzaev commented on apps/vanilla/src/UI/tableView/pagination.ts
> + * @param allAnimeCount All records that the server can provide.
I tried to solve this problem by creating Pagination Service. But I have a need to pass the current page number.

2022-07-14 08:42 UTC, andrey-gazzaev commented on apps/vanilla/src/UI/tableView/pagination.ts
> +
Ok I'll be more careful next time.

2022-07-18 05:22 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-18 05:24 UTC, panov-aleksey-saritasa approved these changes

2022-07-18 07:40 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-18 07:40 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/UI/tableView/table.ts
> +const TABLE_COLUMNS: TableColumnDef[] = [
Don't forget to add readonly for arrays.

2022-07-18 16:47 UTC, pavelzadorin-saritasa approved these changes

2022-07-18 16:47 UTC, pavelzadorin-saritasa commented on libs/core/utils/guards/general.guard.ts
> +  if (typeof value === 'string' && value === '') {
looks like this is falsy condition...

2022-07-18 16:47 UTC, pavelzadorin-saritasa commented on libs/core/utils/guards/general.guard.ts
> +export function isNotFalsy<T>(value: T | null | undefined): value is T {
in general, Boolean does almost the same thing: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean
but for the future, I would recommend using explicit comparisons and more accurately form the model, then you won't need to do a lot of such checks. If null or undefined is not allowed in the field, then it is not necessary to check them for emptiness, including for this we use the typescript.

2022-07-18 16:47 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/types/anime.ts
> +export interface AnimeData {
`AnimeData` translated as `аниме данные`, what is semantic difference with just `Anime`? Use `AnimeList` instead of.

2022-07-18 16:47 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/types/element.ts
> +export interface ElementData {
and again, `Data` is a completely useless word in the names of variables, classes and other storages, they all always store data, i.e. this word does not add any meaning.

2022-07-20 09:53 UTC, merged