Feature/jc19 338 login and register
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #4
Opened 2022-07-07 07:01 UTC by andrey-gazzaev

Created a registration and login page.

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/registration/index.ts
> +    if (tokens instanceof Tokens) {
I dont think this `if` is necessary. Your `registerUser()` method returns only `Promise<Token>`

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/registration/index.ts
> +  const loginForm = document.querySelector<HTMLFormElement>(`.${Registration.FORM}`);
`registrationForm`

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/header.ts
> +/** Sing out from account. */
Who is singing?) Rename sing to sign

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/header.ts
> +    const ID_USER_PROFILE_TEMPLATE = '#user-profile';
Consider using class instead of id. https://wiki.saritasa.rocks/frontend/languages/html#avoid-id

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/header.ts
> +/** Render standard header template. */
Renders

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/constants/form.ts
> +export namespace ErrorMessages {
Maybe `ErrorMessage`?

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/fetches/auth.ts
> +    const URL_LOGIN = 'auth/login/';
Move constants from functions to the top of the file

2022-07-07 08:38 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/localStorage.ts
> +  return null;
```suggestion
return localValue !== null ? JSON.parse(localValue) : null;
```

2022-07-07 13:19 UTC, timofei-maximov-saritasa requested changes

2022-07-07 13:19 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/fetches/user.ts
> +    });
We use `interceptors` to append token to request headers. [Axios docs](https://axios-http.com/docs/interceptors)

2022-07-07 13:19 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/header.ts
> +async function renderUserProfile(access: string): Promise<void> {
You violated abstraction. Your ui shouldn't know anything about access token

2022-07-07 13:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/fetches/instance.ts
> +export const defaultRequestInstance: AxiosInstance = axios.create({
Please avoid type annotation, because its inherited from `axios.create` return type.

2022-07-07 13:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/form.css
> +}
I see that you're removing default html styles. Most likely you will do it on other pages. I suggest using `css-reset` or manually resetting styles globally.

2022-07-07 13:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/form.css
> +  border-bottom: 2px solid var(--form-active-color);
That way, if you change border width, you wouldn't need to change it everywhere.
```suggestion
  border-bottom-color: var(--form-active-color);
```

2022-07-07 13:44 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
> +  --form-background: #fff;
Please group them, use empty line and/or comments.

2022-07-07 14:06 UTC, andrey-gazzaev commented on apps/vanilla/src/fetches/error.ts
> + * Generates predictable error.
The error that comes in is of type "unknown", and this function will convert it to type 'HttpError'.

2022-07-07 14:10 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/fetches/error.ts
> +    const httpError = error as AxiosError<HttpErrorDto>;
Please, use [type guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards)

2022-07-08 06:04 UTC, golovachev-yaroslav approved these changes

2022-07-08 14:16 UTC, andrey-gazzaev commented on apps/vanilla/src/services/general.ts
> +/** Changes header depending on the user. */
Forgot to write a description.

2022-07-11 04:12 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-11 07:17 UTC, kristinaSvobodinaSaritasa approved these changes

2022-07-11 08:15 UTC, elena-dragunova approved these changes

2022-07-12 05:38 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-12 17:08 UTC, timofei-maximov-saritasa requested changes

2022-07-12 17:08 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/general.ts
> +async function isAuthorization<T>(next: () => Promise<T>): Promise<T | boolean> {
According to docs this function should return only `boolean`. Also, let's rename this function to `isAuthorized`

2022-07-12 17:08 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/general.ts
> +}
It's a bit strange that you have header-related logic here.

2022-07-13 06:00 UTC, andrey-gazzaev commented on apps/vanilla/src/services/api/instance.ts
> +defaultRequestInstance.interceptors.response.use(config => config, error => Promise.reject(generateError(error)));
I can't implement it the way how to use the same instance for all requests. Therefore, some requests should not try to refresh the token, for example, when registering, I want to accept an error and process it.

2022-07-13 11:44 UTC, viktor-sakhno-saritasa approved these changes

2022-07-13 11:44 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/UI/header/header.ts
> +  } else if (LocalStorageService.getValue(LocalStorageKey.TOKENS) === null) {
For the future, I think it's a little incorrect that your component knows about local storage. What happens if you want to switch from local storage to another storage? I would advise having some additional intermediate service. In this case, something like `TokenService`. What do you think?

2022-07-14 05:03 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/general.ts
> +    }
I am not sure here, but if backend throws the 401 error on invalid token, consider revising your workflow: you could add an interceptor to the `axios` that would try to refresh token in such cases

2022-07-17 20:56 UTC, dbitkovski approved these changes

2022-07-18 02:37 UTC, merged