Feature/jc19 347 details card
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #7
Opened 2022-07-19 10:35 UTC by andrey-gazzaev

#JC19-347

2022-07-20 10:11 UTC, panov-aleksey-saritasa approved these changes

2022-07-20 10:11 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/details/index.html
> +      <img class="modal-box__image" src="" alt="An anime banner that was opened in a modal window" />
If image is used for decoration purposes only, consider using `alt=""` instead
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-alt

2022-07-20 10:11 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/details/index.html
> +          <a class="profile__list-link link" title="Sign in to account" href="/login/">Sign in</a>
I suppose you could omit `title` here, since anyway it does not bring any new information here

2022-07-20 10:11 UTC, panov-aleksey-saritasa commented on libs/core/models/animeDetails.ts
> +  /** Anime trailer URL.. */
```suggestion
  /** Anime trailer URL. */
```

2022-07-20 10:11 UTC, panov-aleksey-saritasa commented on libs/core/mappers/anime.mapper.ts
> +    });
How about:
```ts
return new AnimeDetails({
  ...AnimeMapper.fromDto(dto),
  // then map AnimeDetails properties
})
```

2022-07-20 10:11 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/domain/queryParams.ts
> +    if (isDefine(id)) {
consider renaming `isDefine` to `isDefined`, since `define` is a verb

2022-07-20 10:27 UTC, andrey-gazzaev commented on apps/vanilla/src/pages/details/index.html
> +      <img class="modal-box__image" src="" alt="An anime banner that was opened in a modal window" />
In the future, a poster should appear in this element

2022-07-20 11:26 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-20 11:26 UTC, gevorg-gevorgyan-saritasa commented on libs/core/dtos/animeDetails.ts
> +  /** Anime trailer URL.. */
```suggestion
  /** Anime trailer URL. */
```

2022-07-20 18:05 UTC, timofei-maximov-saritasa approved these changes

2022-07-20 18:05 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/api/anime.ts
> +  return AnimeMapper.fromDetailsDto(response.data);
```suggestion
  const { data } = await defaultRequestInstance.get<AnimeDetailsDto>(url);

  return AnimeMapper.fromDetailsDto(data);
```

2022-07-20 18:05 UTC, timofei-maximov-saritasa commented on libs/core/models/animeDetails.ts
> +  public readonly airing: boolean;
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#is
```suggestion
  public readonly isAiring: boolean;
```

2022-07-22 01:52 UTC, pavel-romanov8 requested changes

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/UI/auth/registration.ts
> +    !isDefined(lastName) ||
Wow, it looks really heavy) Instead of doing such things manually every time, let's create a function that will accept some array of values and check it for the `isDefined`

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/UI/details/details.ts
> +namespace detailsClass {
Please, use `PascalCase` for namespaces

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/UI/details/details.ts
> + * @param itemText Text inner li.
```suggestion
 * @param itemText List inner text.
```

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/UI/details/details.ts
> +  const imageElement = getDomElement<HTMLImageElement>(document, `.${detailsClass.IMAGE}`);
I see that in most of the cases you are passing the `document` as the first element of the function. Can we make it a default value?

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/UI/tableView/table.ts
> +            tdElement.innerHTML = `${anime[field]}`;
`anime[field]` is being used 3 times here. Let's move it to a variable

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/global/form.css
> +  background: var(--form-background);
Please, avoid background property contraction. You can check more about the reasoning [here](https://www.youtube.com/watch?v=iGkK-5il6Mk&t=1s)

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/details/index.css
> +  background: var(--modal-background-color);
The same thing about `background` shorthand

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/details/index.html
> +  <section class="details">
The section tag should have some heading element that describes the section - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/details/index.html
> +        <ul class="details__list-studios list "></ul>
```suggestion
        <ul class="details__list-studios list"></ul>
```

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/details/index.html
> +        <ul class="details__list-genres list "></ul>
```suggestion
        <ul class="details__list-genres list"></ul>
```

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/services/api/anime.ts
> + * Request to the server to get anime by id.
```suggestion
 * Request to the server to get anime by ID.
```

2022-07-22 01:52 UTC, pavel-romanov8 commented on libs/core/dtos/animeDetails.ts
> +  /** It's on the air. */
```suggestion
  /** Whether it is airing. */
```

2022-07-22 01:52 UTC, pavel-romanov8 commented on apps/vanilla/src/services/general.ts
> +export async function getDetailsAnime(): Promise<AnimeDetails | null> {
```suggestion
export async function getAnimeDetails(): Promise<AnimeDetails | null> {
```

2022-07-23 00:25 UTC, dbitkovski approved these changes

2022-07-24 23:56 UTC, pavel-romanov8 approved these changes

2022-07-25 02:14 UTC, merged