Feature/jc19 407 anime list management [Angular]
saritasa-nest/camp-js-2022-andrey-gazzaev pull request #9
Opened 2022-07-27 11:20 UTC by andrey-gazzaev

#JC19-407

2022-07-27 17:17 UTC, artem-sotnichenko-saritasa requested changes

2022-07-27 17:17 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    this.animeList$ = this.getAnimeList();
You shouldn't reassign observable, but push data into observable. Because every time you recreate and reassign observable, you introduce memory leak.

To fix this, you need to create subjects for pagination, search, etc.. Then combine them together into anime list stream.

Your code should look somehow like this (not an actual solution).
```ts
this.animeList$ = combineLatest(
  search$.pipe(debounceTime(300)),
  filter$,
).pipe(
  switchMap(([search, filter]) => getAnimeList(search, filter))
)
```

That way:
- you won't recreate observable on every change.
- your interfaces will have `readonly`s (you will operate with immutable data).
- your code would be aligned rxjs paradigm.

If you need more explanations, message me in slack.

2022-07-27 17:32 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    this.animeList$ = this.getAnimeList();
As i know `combineLatest` is deprecated, so i would recommend to use `combineLatestWith()`

2022-07-27 17:32 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  public handleSortChange(sort: Sort): void {
Just use `FormControl` instead of `ngModel` for your filter / sort / search. It will allow you to get rid of such handlers and easily get `Observables` via `valueChanges` to combine them

2022-07-27 17:32 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/core/utils/array-equal.ts
> +export default function arraysEqual<T>(s0: T[], s1: T[]): boolean {
Consider using more readable names for arrays

2022-07-27 17:34 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    this.animeList$ = this.getAnimeList();
It's normal to struggle with rxjs (functional paradigm), don't worry, you will get it.

2022-07-27 17:37 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    this.animeList$ = this.getAnimeList();
As i know `combineLatest` is deprecated, so i would recommend to use `combineLatestWith()`

2022-08-02 05:23 UTC, panov-aleksey-saritasa requested changes

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  public readonly typeFilter = new FormControl<string[]>(['TV']);
Can you narrow type here to something more specific instead of `string[]`? For example, `AnimeFilter[]`

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  encapsulation: ViewEncapsulation.None,
Why do you need this? If there is some valid reason for using this, please, leave a comment, otherwise consider revising your approach, components should not leak its styles, it violates whole components ideology

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  direction: SortDirection;
Missing readonly? 🤔

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  isSelect: boolean;
```suggestion
  isSelected: boolean;
```

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  public handlePaginationChange(event: PageEvent): void {
On Angular projects, we are using `on` prefix for handle methods of components
```suggestion
  public onPaginationChange(event: PageEvent): void {
```

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.html
> +          Start of aired
```suggestion
          Start of airing
```

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    const ordering = `${direction}${sortField}`;
Consider creating separate mapper that would transform sort params into ordering object. Also you could make non-anime specific

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +  private setUrl(query: string): void {
Wouldn't it be more convenient to work with object here instead? This way all you have to do is to pass it as `queryParams` into `navigate` method, maybe do some additional mapping stuff

2022-08-02 05:23 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +
This whole query params management stuff is UI-specific thing, consider not doing it in your api methods, they are not responsible for this

2022-08-04 05:44 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  encapsulation: ViewEncapsulation.None,
slack

2022-08-07 16:12 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-07 16:12 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +      }),
Ideally, map functions should be pure. And side effects should be in a `tap`. I suggest refactoring it like so:
```suggestion
      map(([[search, typeFilter, sort], pageNumber]) => {
        const animeListOption = {
          pageNumber,
          sort,
          filter: { byType: typeFilter !== null ? typeFilter : [Type.Tv] },
          search: search !== null ? search : '',
          limit: this.pageSize,
        };
        return this.animeService.getAnimeListHttpParams(animeListOption);
      }),
      tap(animeListHttpParams => urlService.setUrl(animeListHttpParams),
      switchMap(animeListHttpParams => this.animeService.fetchAnimeList(animeListHttpParams))
      tap(() => this.animeListCount = animeList.count)
      map(animeList => animeList.results),
```

2022-08-07 16:12 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    this.setPageSize();
If I understand correctly, you can't make `page` property `readonly`, because you mutating it in a function, and typescript don't understand that you call the function only in a constructor. To fix it, I suggest refactoring it like so 
```suggestion
    this.pageSize = this.getInitialPageSize();
```

2022-08-09 05:43 UTC, viktor-sakhno-saritasa commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +  /** */
Empty comment.

2022-08-09 06:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table-view/table-view.component.html
> +  <div class="table-container mat-elevation-z8">
This class allows you to visually highlight the table

2022-08-09 06:42 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime/table-view/table-view.component.html
> +  <div class="table-container mat-elevation-z8">
This class allows you to visually highlight the table

2022-08-09 13:54 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-08-10 01:15 UTC, viktor-sakhno-saritasa approved these changes

2022-08-10 01:15 UTC, viktor-sakhno-saritasa commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +      tap(() => goToTop()),
It will be great, if you make this side effect explicit, like you did with resetting current page number.

2022-08-10 03:16 UTC, pavel-romanov8 requested changes

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +namespace DefaultParamValue {
Can it be just dictionary? Looks like a `namespace` too much for it

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table-view/table-view.component.html
> +                  *ngFor="let filter of filterListByType"
Add `trackBy` function

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  private readonly currentPageNumberInitialValue = this.animeListOptions.pageNumber;
Not sure why do we need the field since we can initialize the `currentPageNumber$` with it directly

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +        this.sort$.pipe(skip(1)),
This usage of `skip` cased by `startWith` operator. Can it be improved in order to avoid such cumbersome flow?

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  private getInitialFilterListByType(): readonly FilterItem[] {
Don't force function customers to work with read-only outputs. Let them decide you to treat it

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +      combineLatestWith(
Not sure why do we need to use `combineLatestWith` when we can use just `combineLatest`

2022-08-10 03:16 UTC, pavel-romanov8 commented on apps/angular/src/core/models/anime-list-options.ts
> +  direction: string;
```suggestion
  readonly direction: string;
```

2022-08-11 04:59 UTC, chernodub requested changes

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  );
Since you never use `searchInitialValue` in the component except these 3 lines, why making it a property? Please simplify the component by reducing the amount of properties, now it's very hard to read

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  );
Consider grouping your type filter + search vlaue into a single entity, let's say `Query`. This way you'll reduce the coupling of this "querying" with the component

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/guards/type-array.ts
> +import { Type } from '@js-camp/core/models/anime';
Seems like `Type` is too generic name for Angular application. As far as I remember, angular already provides such an entity. Consider scoping your name better, either via some naming convention or a namespace

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/anime.service.ts
> +  public getAnimeTypes(): string[] {
Usually, such dictionaries are fetched from the BE. So, for better maintainability (in case your team ever decide not to store it in FE code), I recommend making it async

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/anime.service.ts
> +  public animeListOptionsToHttpParams(animeListOptions: AnimeListOptions): HttpParams {
As far as I remember, HTTP params is an entity specific to Angular HTTP module. So, you must not expose it. If you need this stuff for browser URL, consider using `URLSearchParams`

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +    const params = this.route.snapshot.queryParams;
This is an interesting solution, getting the params from query params. But, usually, our mappers never know anything about the UI-related entities. Router is also bound to the UI layer since it directly manipulates the components.

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +      .set(ParamName.Search, search);
Actually, you could just create an object, and on service layer, you could create the `HttpParams` form this object. By doing that, you'll uncouple your mapper from the framework-provided entity

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +    return DefaultParamValue.LIMIT;
Usually, mapper should not provide any default state (or just state). Their responsibility is to be a function, that transforms DTO to domain and back, without having any state

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/url.service.ts
> +  public setUrl(httpParams: HttpParams): void {
@andrey-gazzaev please also see my comment in `apps/angular/src/core/services/anime.service.ts`

2022-08-11 04:59 UTC, chernodub commented on apps/angular/src/core/services/url.service.ts
> +    });
`URLSearchParams` could parse that for you, please consider using it

2022-08-11 04:59 UTC, chernodub commented on apps/angular/tsconfig.json
> +    "noFallthroughCasesInSwitch": true,
Usually, this is not a valid JSON. So I recommend you to be very careful with trailing commas here

2022-08-11 04:59 UTC, chernodub commented on apps/angular/tsconfig.json
> +    "noFallthroughCasesInSwitch": true,
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#trailing_commas_in_json

2022-08-11 04:59 UTC, chernodub commented on libs/core/utils/types/sort.ts
>  export interface Sort<Order, Field> {
To explicitly show that types inferred from generic are related to current context, we use prefix `T` (e.g: `TParams`). Check out [Microsoft's explanation](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces?redirectedfrom=MSDN#names-of-generic-type-parameters)

2022-08-15 03:17 UTC, chernodub requested changes

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +          types: typeFilter !== null ? typeFilter : [],
Seems like you don't need `null` values after all

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +      tap(animeListParams => this.setQueryParamsToUrl(animeListParams)),
Probably it would be a good idea making this side effect explicit https://wiki.saritasa.rocks/frontend/frameworks/angular/best-practices#make-your-side-effects-explicit

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +        return animeList.results;
I guess you could just store a `{count, items}` object instead of just an array + numeric?

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  private initializationAnimeList(): Observable<readonly AnimeBase[]> {
Please make sure your methods/functions have verbs https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/core/guards/type-array.ts
> +export function isTypeArray(array: string[]): array is AnimeType[] {
Pls give it a more specific name, or isolate it in the namespace. `isType` and `isTypeArray` are too generic. e.g.: Angular also provides `Type` https://angular.io/api/core/Type, so this may be confising for some devs

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/core/models/anime-list-query-params.ts
> +  readonly ordering: string;
`ordering` and `direction` seem like they mean the same thing. Should you improve the name?

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/core/models/anime-list-query-params.ts
> +  readonly direction: SortDirection;
Since these properties are very coupled, would it be more reasonable to unify it in a single entity?

2022-08-15 03:17 UTC, chernodub commented on apps/angular/src/core/services/app-config.service.ts
> +  public readonly apiCampKey: string = environment.apiCampKey;
What's the point name-scoping this ? :)

2022-08-16 02:27 UTC, chernodub approved these changes
Approved for merge, but pls fix the comments first

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  readonly search: FormControl<string | ''>;
Pls see the resulting type of these properties. `''` is going to be consumed by `string`. The same for array above

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  public readonly formQuery: FormGroup<QueryFormControls>;
`formQuery` sounds like you're querying some form. I'd go with `queryForm`

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    });
Please prefer `FormBuilder` for creating form to avoid boilerplate

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +    };
You sure you need this const?
I believe it's already obvious that it's an initial value, since you pass it to a constructor :)

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/app/features/anime/table-view/table-view.component.ts
> +  public trackItemAnime(index: number, anime: AnimeBase): number {
seems like `item` in the name of this method does not bring any semantic value, right?

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/core/models/anime-list-query-params.ts
> +    readonly direction: SortDirection;
1. Seems like your domain entity depends on UI-provided one - `SortDirection`. Consider resolving this to uncouple your layers
2. Since these two properties always come in pair and don't make sense without each other, why not unifying them in a single entity?

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/core/services/anime.service.ts
> +  // eslint-disable-next-line require-await
When disabling eslint rule, please always specify why it is done. If we ignore the rules without a reason, seems like we don't even need the rules

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/core/services/mappers/anime-list-options.mapper.ts
> +export class AnimeListOptionsMapper {
As far as I understand, your mappers are namespaces in `common` lib. Why not continue using this approach to reuse this stuff in your next app? Pls try to be consistent, this way you'll make your apps way more understandable/predictable :)

2022-08-16 02:27 UTC, chernodub commented on apps/angular/src/theme/styles.css
> +  width: 150px;
I'd recommend scoping this into a file, in order to be able easily distinguish such stuff. Otherwise, this global file could become a mess in the future.

2022-08-16 05:16 UTC, merged